### PR TITLE
Added Safari Extension

### PR DESCRIPTION
**Pull request by richrad**
Hey! Love this but I use Safari, so I just copied everything into a new 'safari' folder and made the couple changes to make it work.

### CODE REVIEW

**Comment by carolinehermans** [comment]
This is so cool! Thanks for doing this. I don't have an Apple Developer account, so I'm not sure I'll be able to publish the extension in Safari. What would the next steps be for making it live?

**Comment by richrad** [comment]
Now that I think about it I've never actually gone all the way to submitting to the Safari Extensions Gallery so I'm not super sure what all the steps are! I *think* you used to be able to get a certificate to sign Safari extensions without a paid developer account but I'm looking at the documentation now and already getting a little confused – it's harder to search now that there are Safari *App* Extensions in addition to regular 'ol extensions. I'll try to look into it more later but here's a link to the builder docs if you want to poke around: [https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/UsingExtensionBuilder/UsingExtensionBuilder.html](https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/UsingExtensionBuilder/UsingExtensionBuilder.html)

**Comment by carolinehermans** [comment]
Ahhh alright, that makes total sense. Well I'll accept your changes and keep the safari folder in there, and if people want to install it for themselves locally they'll be able to! (Until I figure out Apple's developer program)

**Review by carolinehermans — APPROVED** [review]
thanks for doing this!

**Pull request merged**
